data:
  train_batch_size: 2
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 1  # this is also val batch size
  train_files: sft_data.parquet
  val_files: sft_data.parquet
  prompt_key: question
  response_key: answer
  # Multi-turn settings
  multiturn:
    enable: True  # to use multi-turn dataset
    messages_key: messages 
  custom_cls:
    path: null
    name: null
  max_length: 16384  
  truncation: right
  balance_dp_token: False
  chat_template: null
model:
  partial_pretrain: Qwen/Qwen2.5-Math-7B-Instruct
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: True
  trust_remote_code: True
  lora_rank: 0 
  lora_alpha: 16  
  target_modules: all-linear  
  use_liger: False
  strategy: fsdp2
optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0
ulysses_sequence_parallel_size: 1
use_remove_padding: False
trainer:
  default_local_dir: outputs/qwen2.5_math_sft
  default_hdfs_dir: null
  resume_path: null
  project_name: math-tool-sft
  experiment_name: qwen2.5-math-7b
  total_epochs: 3
  total_training_steps: null
  logger: ['console']
  seed: 1

